{{- if .Values.tolgee.managedCertificate.enabled -}}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "tolgee.fullname" . }}
spec:
  domains:
    {{- range .Values.tolgee.managedCertificate.domains}}
    - {{. | quote}}
    {{- end}}
{{- end}}
