name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_dir: /